"""Comic generation models.

Contains both backend-only models (Storyboard, VisualAnchors) for prompt building
and API-exposed models (GeneratedComic, GeneratedPage) for responses.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from vulnerable_banana.models.base import ApiModel

# Type aliases for archetypes and art styles
Archetype = Literal["HEIST", "OOPS", "SAGA", "LURKER"]
ArtStyle = Literal[
    "EPIC_SCIFI",
    "NOIR_THRILLER",
    "RETRO_COMIC",
    "MINIMAL_XKCD",
    "CYBERPUNK",
    "PROPAGANDA_POSTER",
]


# =============================================================================
# Backend-only models for storyboard generation (not exposed to API)
# =============================================================================


class PanelDescription(BaseModel):
    """Description of a single comic panel. Backend-only."""

    panel_number: int
    scene_description: str  # Detailed visual description for image generation
    dialogue: str | None = None  # Speech bubbles
    caption: str | None = None  # Narrator text


class ComicPage(BaseModel):
    """A single page of the comic (one generated image). Backend-only."""

    page_number: int
    beats: list[str]  # Story beats covered on this page
    layout: str  # e.g., "2x2 grid", "3 panels horizontal"
    panels: list[PanelDescription]  # 1-6+ panels per page


class CharacterDesign(BaseModel):
    """Consistent character description for visual continuity. Backend-only."""

    name: str  # "The Developer"
    first_appears: int  # Page number where character first appears
    appearance: str  # "Young person, round glasses, dark hoodie, tired eyes"
    recurring_props: list[str] = Field(default_factory=list)  # ["coffee cup", "laptop"]


class VisualAnchors(BaseModel):
    """Consistent visual elements across all pages. Backend-only."""

    color_palette: list[str]  # ["Desert orange #D2691E", "Sand beige #F4A460"]
    characters: list[CharacterDesign]  # All recurring characters
    key_entities: list[str]  # ["Shai-Hulud: colossal sandworm with circuit patterns"]
    atmosphere: str  # "Ominous, vast, desert heat haze"
    line_style: str  # "Bold outlines, Moebius-style hatching"


class Storyboard(BaseModel):
    """Complete storyboard for comic generation. Backend-only.

    Generated by the storyboard agent and used to build image prompts.
    """

    title: str
    archetype: Archetype
    art_style: ArtStyle
    style_modifiers: str  # e.g., "desert palette, sandworm motifs"
    visual_anchors: VisualAnchors  # For consistency across pages
    pages: list[ComicPage]  # 3-10 pages


# =============================================================================
# API-exposed models
# =============================================================================


class GeneratedPage(ApiModel):
    """A single generated page image."""

    page_number: int
    image_url: str  # URL to the page image


class GeneratedComic(ApiModel):
    """A generated comic ready for viewing."""

    comic_hash: str
    title: str
    archetype: Archetype
    art_style: ArtStyle
    page_count: int
    total_panels: int
    pages: list[GeneratedPage]  # All page images
    share_url: str
    generated_at: datetime


class ComicMetadata(ApiModel):
    """Comic metadata for OG tags and share pages."""

    comic_hash: str
    title: str
    description: str
    page_count: int
    pages: list[GeneratedPage]
    thumbnail_url: str  # Points to page 1 for social media previews
    generated_at: datetime
